services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=electronic_ecommerce'
      - 'MYSQL_ROOT_PASSWORD=12345678'
    ports:
      - '3306'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=12345678'
    ports:
      - '5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
