version: '3.8'
services:
  docker-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: electronic_ecommerce
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - app-network
#  docker-postgres:
#    image: postgres:latest
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: ommanisoft
#      POSTGRES_DB: ommani_vubm
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U root" ]
#      timeout: 20s
#      retries: 10
#    networks:
#      - app-network
#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: intern@ommani.vn
#      PGADMIN_DEFAULT_PASSWORD: ommanisoft
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    ports:
#      - "8080:80"
#    depends_on:
#      - docker-postgres
#    networks:
#      - app-network
  nginx:
    image: nginx
    ports:
      - "90:90"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - app-network
  app:
    build:
      context: .
      dockerfile: Dockerfile
#    depends_on:
#      docker-mysql:
#        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
    command: mvn spring-boot:run -Dspring-boot.devtools.restart.enabled=true
    networks:
      - app-network


  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 1234
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: docker-mysql
      PMA_PASSWORD: 1234
    networks:
      - app-network
networks:
  app-network:
    driver: bridge